# Generated by Django 3.2.25 on 2024-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderPizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_course', models.TextField(max_length=200)),
                ('second_course', models.TextField(max_length=200)),
                ('drink', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
            ],
        ),
    ]
