# Generated by Django 5.0.3 on 2024-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderPizza', '0003_alter_dailymenu_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Mo'), ('TUESDAY', 'Tu'), ('WEDNESDAY', 'We'), ('THURSDAY', 'Th'), ('FRIDAY', 'Fr'), ('SATURDAY', 'Sat'), ('SUNDAY', 'Su')], default='MONDAY', max_length=9),
        ),
    ]
