# Generated by Django 5.0.3 on 2024-03-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
